sudo: false

language: c

compiler: gcc

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libarpack2-dev

before_script:
  - mkdir build
  - cd build 
  - cmake -D SUPERLU=OFF ..

script:
  - make
