sudo: false

language: cpp

compiler: gcc

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libarpack2-dev

env:
  - SUPERLU=ON BLAS=SYSTEM

before_script:
  - if [ "$SUPERLU" == "ON" ]; then ./install-superlu.sh ; fi
  - mkdir build
  - cd build 
  - cmake -D SUPERLU=$SUPERLU ..

script:
  - make
