sudo: false

language: cpp

compiler: gcc

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libarpack2-dev

env:
  - SUPERLU=ON BLAS=SYSTEM

before_install:
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gcc homebrew/science/arpack ; fi

before_script:
  - if [ "$SUPERLU" == "ON" ]; then ./install-superlu.sh ; fi
  - mkdir build
  - cd build 
  - cmake -D SUPERLU=$SUPERLU ..

script:
  - make
